### ISSUE TITLE
How to install in Ubuntu or linux ? 

### ISSUE THREAD

**Issue by ingnelson** [domosekai/turnout#1]
Hello sir.

can you give me the commands to install it and run it on Ubuntu , PLEASE ?

I really want to use it , but i am new on Linux , I  just buy a VPS ubuntu , i want to install it and run your proxy on port 8043.

Please i really want to use it .

Help me with all the commnads to install it and run it .

**Comment by domosekai** [comment]
What are you going to achieve? This program is not supposed to be running on VPS. It's a local proxy.

**Comment by ingnelson** [comment]
@domosekai I want to bypass a firewall .

i have a SSH server listening on port 442  on my VPS , so I need a proxy server that listen on port 8043 to create a tunnel to bypass my firewall.

client (android) > proxy on port 8043 send the request with CONNECT method > SERVER SSH on port 442 

Similar to this : 

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)


I hope you can help to create a proxy that send a http response : 

HTTP/1.1 200 Connection established\r\n\r\n

I will wait for reply

**Comment by domosekai** [comment]
If I understand correctly, you want to access the ssh port which is blocked by the firewall. So you need a http proxy on 8043 to divert the connection. Then you should use a normal proxy (such as squid) instead of my program. Have you tried that?2020/07/08 午前11:55 Nelson <notifications@github.com>:
@domosekai I want to bypass a firewall .
i have a SSH server listening on port 442  on my VPS , so I need a proxy server that listen on port 8043 to create a tunnel to bypass my firewall.
client (android) > proxy on port 8043 send the request with CONNECT method > SERVER SSH on port 442
Similar to this :


I hope you can help to create a proxy that send a http response :
HTTP/1.1 200 Connection established\r\n\r\n
I will wait for reply

**Comment by ingnelson** [comment]
@domosekai i tried before with squid + but the firewall do not let pass the request .

On my VPS acept the connection from the client IP , but when the server send the response to the client , the response never came to the client .

by the way, the only proxy that works is : ` 50.18.211.227:8043 `
This proxy send back a response : 
```
HTTP/1.1 200 Connection established
Server: sdgw

```

is this proxy is a Nginx proxy ?   because it send a response : Server: sdgw    ???

if the answer is yes , it can be a forward or reverse proxy ?

**Comment by domosekai** [comment]
I don't know what that is. I guess the firewall is not an HTTP proxy, right? Then you should be able to browse https sites directly?
If so you can make SSH over TLS by using stunnel. So your traffic will appear as normal TLS to the firewall. 
Link for reference:
https://www.unixmen.com/tunnel-ssh-connections-ssl-using-stunnel-debian-7-ubuntu-13-10/
