### ISSUE TITLE
CPU使用率有点太高了

### ISSUE THREAD

**Issue by jojo147** [domosekai/turnout#2]
用在树莓派 4B上
CPU使用率  8～90％
是不是太高了
是我这里自己的问题吗 ？

**Comment by jojo147** [comment]
我错了
CPU 使用高  是我透明代理没写好的的问题

**Comment by domosekai** [comment]
Glad you figured it out. Let me still give you some reference because without knowing the traffic load I can't comment if it's high.
My router has a single-core A9 CPU at 800 MHz. It's pretty weak compared to the 4B.
When I watch Youtube 1080p on the computer the average load on router is about 20%.
